export const tablaSources = {
    order:{
        columns:[
            {
                field: 'id',
                headerName:'ID',
            },
            {
                field: 'product', // Cambiado de 'producto' a 'product'
                headerName: 'Producto',
            },
            {
                field: 'customer',
                headerName: 'Cliente',
            },
            {
                field: 'date',
                headerName: 'Fecha',
            },
            {
                field: 'amount',
                headerName: 'Monto',
            },
            {
                field: 'method',
                headerName: 'Metodo de Pago',
            },
            {
                field: 'status',
                headerName: 'Estado',
            },    
        ],
        rows: [
            {
              id: 1143155,
              product: "Vestido Verano (Verde)",
              img:  "https://images.pexels.com/photos/5617671/pexels-photo-5617671.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Camila Lannister",
              date: "1 Marzo",
              amount: 785,
              method: "Pago Contra Entrega",
              status: "Aprobado",
              location: "Tienda",
            },
            {
              id: 2235235,
              product: "Vestido Amarillo",
              img: "https://images.pexels.com/photos/14541223/pexels-photo-14541223.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Rosa Elizondo",
              date: "15 Marzo",
              amount: 900,
              method: "Pago En Linea",
              status: "Pendiente",
              location: "Tienda",
            },
            {
              id: 2342353,
              product: "Vestido Amarillo",
              img: "https://images.pexels.com/photos/14541223/pexels-photo-14541223.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Jose Aryan",
              date: "1 Abril",
              amount: 35,
              method: "Pago Contra Entrega",
              status: "Pendiente",
              location: "Tienda",
            },
            {
              id: 2357741,
              product: "Vestido Fosfo Naranja",
              img: "https://images.pexels.com/photos/19662126/pexels-photo-19662126/free-photo-of-sus-sonrisas.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Marisa Lannister",
              date: "3 Abril",
              amount: 920,
              method: "En Linea",
              status: "Aprobado",
              location: "Tienda",
            },
            {
              id: 2342355,
              product: "Vestido Fosfo Naranja",
              img: "https://images.pexels.com/photos/19662126/pexels-photo-19662126/free-photo-of-sus-sonrisas.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Melissa Frances",
              date: "11 Abril",
              amount: 2000,
              method: "En Linea",
              status: "Pendiente",
              location: "Tienda",
            },
        ],
    },
    delivery:{
        columns:[
            {
                field: 'id',
                headerName:'ID',
            },
            {
                field: 'product', // Cambiado de 'producto' a 'product'
                headerName: 'Producto',
            },
            {
                field: 'customer',
                headerName: 'Cliente',
            },
            {
                field: 'date',
                headerName: 'Fecha',
            },
            {
                field: 'amount',
                headerName: 'Monto',
            },
            {
                field: 'method',
                headerName: 'Metodo de Pago',
            },
            {
                field: 'location',
                headerName: 'Lugar',
            },    
        ],
        rows: [
            {
              id: 1143155,
              product: "Vestido Verano (Verde)",
              img:  "https://images.pexels.com/photos/5617671/pexels-photo-5617671.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Camila Lannister",
              date: "1 Marzo",
              amount: 785,
              method: "Pago Contra Entrega",
              location: "Tienda",
              status: "Aprobado",
            },
            {
              id: 2235235,
              product: "Vestido Amarillo",
              img: "https://images.pexels.com/photos/14541223/pexels-photo-14541223.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Rosa Elizondo",
              date: "15 Marzo",
              amount: 900,
              method: "Pago En Linea",
              location: "Ruta",
              status: "Pendiente",
            },
            {
              id: 2342353,
              product: "Vestido Amarillo",
              img: "https://images.pexels.com/photos/14541223/pexels-photo-14541223.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Jose Aryan",
              date: "1 Abril",
              amount: 35,
              method: "Pago Contra Entrega",
              location: "Ruta",
              status: "Pendiente",
            },
            {
              id: 2357741,
              product: "Vestido Fosfo Naranja",
              img: "https://images.pexels.com/photos/19662126/pexels-photo-19662126/free-photo-of-sus-sonrisas.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Marisa Lannister",
              date: "3 Abril",
              amount: 920,
              method: "En Linea",
              location: "Ruta",
              status: "Aprobado",
            },
            {
              id: 2342355,
              product: "Vestido Fosfo Naranja",
              img: "https://images.pexels.com/photos/19662126/pexels-photo-19662126/free-photo-of-sus-sonrisas.jpeg?auto=compress&cs=tinysrgb&w=600",
              customer: "Melissa Frances",
              date: "11 Abril",
              amount: 2000,
              method: "En Linea",
              location: "Tienda",
              status: "Pendiente",
            },
        ],
    },
}